Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/RedundantFetchBlock:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/GlobalStdStream:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/HashSyntax:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/PerlBackrefs:
  Enabled: false
Layout/EndOfLine:
  Enabled: false
Layout/LineLength:
  Enabled: false
Layout/EmptyLinesAroundBlockBody:
  Enabled: false
Layout/EmptyLines:
  Enabled: false
Layout/TrailingEmptyLines:
  Enabled: false
Layout/TrailingWhitespace:
  Enabled: false
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false
Layout/ExtraSpacing:
  Enabled: false
Layout/EmptyLinesAroundClassBody:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/ArgumentAlignment:
  Enabled: false
Layout/SpaceAroundOperators:
  Enabled: false
Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false
Lint/ScriptPermission:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
